config/routes.rb
FullcalendarAssets::Application.routes.draw do
  resources :teams

  resources :todos  do
      collection { post :sort }
    end

  resources :projects   do
        collection { post :sort }
      end

  resources :eventitems
  resources :projectevents
  resources :users

  resource :calendar, :only => [:show]

  resource :projectcalendar, :only => [:show]

  resources :events
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  resources :sessions
  resources :password_resets

  match 'projectsearch' => 'projects#search'
  match 'myprojects' => 'projects#my_projects'
  match 'mytodos' => 'todos#my_todos'
  match 'projectcopy/:id' => 'projects#copy'
  match 'projects/:action/:title' => 'projects#index'
  match 'project/show_todos/:id' => 'projects#show_todos'
  match 'project/report/:id' => 'projects#report'
  match 'projects/:id' => 'projects#show'
  match 'projects/:id' => 'projects#sort'
  match 'projectevents/new/:id' => 'projectevents#new'
  match 'projectevent/:id' => 'projectevents#showmilestone'
  match 'todos/new/:id' => 'todos#new'
  match 'todo/:id' => 'todos#show'

  root :to => 'home#index'

end

app/models/project.rb
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          class Project < ActiveRecord::Base
  belongs_to :user
  has_many :projectevents
  has_many :todos
  attr_accessible :all_day, :className, :color, :description, :ends_at, :starts_at, :title, :projectlink, :user_id, :state


  scope :between, lambda {|start_time, end_time|
    {:conditions => ["? < starts_at < ?", Project.format_date(start_time), Project.format_date(end_time)] }
  }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def search
      @projectsearch = params[:title]
      redirect_to :action => 'index', :title => @projectsearch
    end
  # GET /projects
  # GET /projects.json
  def index
    if params[:title] != nil then
    @projectsearch = params[:title]+"%"
    else
      @projectsearch ="%"
    end

    @projects = Project.all(:conditions => ["team_id = #{current_user.team_id} and title like ?","#{@projectsearch}"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @projects }
    end
  end


  def my_projects
    @projects = Project.all(:conditions => ["user_id = #{current_user.id}"])
    respond_to do |format|
          format.html # index.html.erb
          format.json { render :json => @projects }
        end
  end


  # GET /projects/1
  # GET /projects/1.json
  def show

    @project = Project.find(params[:id])
        id=params[:id]
            @projectevents = Projectevent.find_all_by_eventtype_and_project_id("milestone",id)
            @todos = Todo.order("position").find_all_by_project_id(id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @project }
    end
  end

  def add_milestone
           projectid=params[:project]
           redirect_to "/projectevents/new/#{projectid}"

  end




  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    id=params[:id]
    @projectevents = Projectevent.find_all_by_eventtype_and_project_id("milestone",id)
    @todos = Todo.find_all_by_project_id(id)

    respond_to do |format|
          format.html # show.html.erb
          format.json { render :json => @project }
    end

  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @team_id = current_user.team_id
    @project.all_day = "true"
    @project.team_id = @team_id
    @state = params[:project][:state]

    if @state == "offen"
                  @project.color =="darkblue"
                elsif @state =="aktiv"
                  @project.color = "darkgreen"
                elsif @state =="in Arbeit"
                     @project.color = "orange"
                elsif @state =="kritisch"
                     @project.color = "darkred"
                elsif @state =="fertig"
                     @project.color = "darkgrey"
                end

    @projectevent = Projectevent.new(params[:project])

    respond_to do |format|
      if @project.save


        @project.save
        @projectevent.project_id = @project.id
        @projectevent.team_id = @team_id
        @projectevent.eventtype = "project"
        #@projectevent.color= "darkgrey"
        @projectevent.all_day = "true"
        @projectevent.color = @project.color
         @projectevent.save
        format.html { redirect_to @project, :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    id = params[:id]
    @state = params[:project][:state]

        if @state == "offen"
                      @project.color =="darkblue"
                    elsif @state =="aktiv"
                      @project.color = "darkgreen"
                    elsif @state =="in Arbeit"
                         @project.color = "orange"
                    elsif @state =="kritisch"
                         @project.color = "darkred"
                    elsif @state =="fertig"
                         @project.color = "darkgrey"
                    end


    @projectevent = Projectevent.find_by_eventtype_and_project_id("project" , id)

    respond_to do |format|
      if @project.update_attributes(params[:project])

        @projectevent.update_attributes(params[:project])
        @projectevent.color = @project.color
        @projectevent.save

        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def copy
    @source_project = Project.find(params[:id])
    @milestones = Projectevent.all(:conditions => ["project_id = ?",@source_project.id])
    @todos = Todo.all(:conditions => ["project_id = ?",@source_project.id])
    @dest_project = Project.new
    @dest_project.title = "Copy of" + @source_project.title
    @dest_project.description = "copy of " + @source_project.description
    @dest_project.starts_at = @source_project.starts_at
    @dest_project.ends_at = @source_project.ends_at
    @dest_project.user_id = current_user.id
    @dest_project.team_id = current_user.id
    @dest_project.save
    @project_id = @dest_project.id
    @milestones.each do |milestone|
      @milestone = Projectevent.new
      @milestone.title = milestone.title
      @milestone.starts_at = milestone.starts_at
      @milestone.ends_at = milestone.ends_at
      @milestone.description = milestone.description
      @milestone.eventtype = milestone.eventtype
      @milestone.user_id = milestone.user_id
      @milestone.team_id = milestone.team_id
      @milestone.color = milestone.color
      @milestone.project_id = @project_id
      @milestone.save
    end

    @todos.each do |todo|
          @todo = Todo.new
          @todo.todotitle = todo.todotitle
          @todo.description = todo.description
          @todo.user_id = todo.user_id
          @todo.team_id = todo.team_id
          @todo.project_id = @project_id
          @todo.position = todo.position
          @todo.save
    end
    redirect_to @dest_project
  end


  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def sort
    index=1
    params[:todo].each do |id|
       @todo = Todo.find_by_id(id)
        @todo.position = index
       @todo.save
       index=index+1
      end
     render :nothing => true
   end

  def report

    @project = Project.find(params[:id])
           id=params[:id]
           user= User.find(@project.user_id)
           @username = user.firstname  + " " +user.name
           @projectevents = Projectevent.find_all_by_eventtype_and_project_id("milestone",id)

          @todos = Todo.order("position").find_all_by_project_id(id)
     #@project="Hallo"
          pdf=ProjectPdf.new(@project, @projectevents, @todos, @username)
          send_data pdf.report, :filename => "Projectreport ",
                    :type => "application/pdf",
                    :disposition => "inline"


  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
        <%= f.label :title, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :title, :class => 'text_field' %>
        </div>
    </div>


    <div class="control-group">
        <%= f.label :username, :class => 'control-label' %>
        <div class="controls">
            <%= collection_select(:project, :user_id,
                                  User.all(:order => 'firstname'), :id, :firstname) %>
        </div>
    </div>

    <div class="control-group">
        <%= f.label :starts_at, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :starts_at, :class => 'datetime_select' %>
        </div>
    </div>


    <div class="control-group">
        <%= f.label :ends_at, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :ends_at, :class => 'datetime_select' %>
        </div>
    </div>
    <div class="control-group">
               <%= f.label :status, :class => 'control-label' %>
             <div class="controls">
               <%= select(:project, :state, [@project.state,
                                "offen",
                                "aktiv",
                                "in Arbeit",
                                "kritisch",
                                "fertig"]) %></td>
             </div>
    <div class="control-group">
        <%= f.label :description, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_area :description, :class => 'text_area', :rows => 5 %>
        </div>
    </div>

    <div class="control-group">
                <%= f.label :projektlink, :class => 'control-label' %>
                <div class="controls">
                    <%= f.text_field :projectlink, :class => 'text_area', :rows => 5 %>
                </div>
        </div>

    <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    projectevents_path, :class => 'btn' %>
    </div>

        <ul id="myTab" class="nav nav-tabs" data-tabs="tabs">
            <li class="active"><a href="#milestones" data-toggle="tab">Milestones</a></li>
            <li><a href="#todos" data-toggle="tab">Todos</a></li>
        </ul>
            <div class="tab-content">
              <div class="tab-pane fade in " id="milestones">
                <%- model_class2 = Projectevent -%>

                <h3> Project-Milestones</h3>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Milestone</th>
                        <th>Beginn</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th><%= t '.actions', :default => t("helpers.actions") %></th>
                    </tr>
                    </thead>
                    <%if @projectevents =! []  %>
                      <% @projectevents.each do |projectevent| %>
                        <tr>
                            <td>
                                <span class="badge badge-info">Milestone</span> <a href=<%= "/projectevent/#{projectevent.id}" %> ><%= projectevent.title %></a>

                            </td>
                            <td><%= projectevent.starts_at.strftime("%d.%m.%y") %></td>
                            <td><%= projectevent.ends_at.strftime("%d.%m.%y") %></td>
                            <td><%= projectevent.state %></td>

                            <td>
                                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                            edit_projectevent_path(projectevent), :class => 'btn btn-mini' %>
                                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                            projectevent_path(projectevent),
                                            :method => :delete,
                                            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                                            :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>
                      <% end %>
                    <% end %>
                    </tbody>
                </table>

                <%= link_to t('.new', :default => t("helpers.links.neuer_milestone")),
                            "/projectevents/new/#{@project.id}",
                            :class => 'btn btn-primary' %>
            </div>




        <%- model_class = Todo -%>



            <div class="tab-pane fade in active" id="todos">
                <h2><%= t '.title', :default => model_class.model_name.human.pluralize %></h2>

                <table class="table table-striped" id="todosX">
                    <thead>
                    <tr>
                        <th></th>

                        <th>User</th>
                        <th>Status</th>
                        <th><%= t '.actions', :default => t("helpers.actions") %></th>
                    </tr>
                    </thead>
                    <tbody>
                    <%if @ptodos =! []  %>
                    <% @todos.each do |todo| %>

                        <tr class="todos" id="todo_<%= todo.id %>">
                            <% if todo.state=="offen"; @badge= "badge-important"; end %>
                            <% if todo.state=="in Arbeit"; @badge= "badge-warning"; end %>
                            <% if todo.state=="fertig"; @badge= "badge-success"; end %>

                            <td>
                                    <span class="badge <%= "#{@badge}" %>">ToDo</span>


                                <%= link_to todo.todotitle, todo_path(todo) %>
                            </td>

                            <td><%= todo.user.firstname %></td>
                            <td><%= todo.state %></td>

                            <td>
                                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                            edit_todo_path(todo), :class => 'btn btn-mini' %>
                                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                            todo_path(todo),
                                            :method => :delete,
                                            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                                            :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>

                    <% end %>
                    <% end %>

                    </tbody>
                </table>

                <%= link_to t('.new', :default => t("helpers.links.neues Todo")),
                            "/todos/new/#{@project.id}",
                            :class => 'btn btn-primary' %>
            </div>
           </div>

<% end %>

app/views/projects/_form_edit.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
        <%= f.label :title, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :title, :class => 'text_field' %>
        </div>
    </div>


    <div class="control-group">
        <%= f.label :username, :class => 'control-label' %>
        <div class="controls">
            <%= collection_select(:project, :user_id,
                                  User.all(:order => 'firstname'), :id, :firstname) %>
        </div>
    </div>

    <div class="control-group">
        <%= f.label :starts_at, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :starts_at, :class => 'datetime_select' %>
        </div>
    </div>


    <div class="control-group">
        <%= f.label :ends_at, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :ends_at, :class => 'datetime_select' %>
        </div>
    </div>
    <div class="control-group">
           <%= f.label :status, :class => 'control-label' %>
         <div class="controls">
           <%= select(:project, :state, [@project.state,
                            "offen",
                            "aktiv",
                            "in Arbeit",
                            "kritisch",
                            "fertig"]) %></td>
         </div>

       </div>
    <div class="control-group">
        <%= f.label :description, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_area :description, :class => 'text_area', :rows => 5 %>
        </div>
    </div>

    <div class="control-group">
            <%= f.label :projektlink, :class => 'control-label' %>
            <div class="controls">
                <%= f.text_field :projectlink, :class => 'text_area', :rows => 5 %>
            </div>
    </div>

    <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    projectevents_path, :class => 'btn' %>
    </div>

        <ul id="myTab" class="nav nav-tabs" data-tabs="tabs">
            <li class="active"><a href="#milestones" data-toggle="tab">Milestones</a></li>
            <li><a href="#todos" data-toggle="tab">Todos</a></li>
        </ul>
            <div class="tab-content">
              <div class="tab-pane fade in active" id="milestones">
                <%- model_class2 = Projectevent -%>

                <h3> Project-Milestones</h3>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Milestone</th>
                        <th>Beginn</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th><%= t '.actions', :default => t("helpers.actions") %></th>
                    </tr>
                    </thead>

                    <% @projectevents.each do |projectevent| %>
                        <tr>
                            <td>
                                <span class="badge badge-info">Milestone</span> <a href=<%= "/projectevent/#{projectevent.id}" %> ><%= projectevent.title %></a>
                            </td>
                            <td><%= projectevent.starts_at.strftime("%d.%m.%y") %></td>
                            <td><%= projectevent.ends_at.strftime("%d.%m.%y") %></td>
                            <td><%= projectevent.state %></td>

                            <td>

                                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                            edit_projectevent_path(projectevent), :class => 'btn btn-mini' %>
                                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                            projectevent_path(projectevent),
                                            :method => :delete,
                                            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                                            :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>
                    <% end %>

                    </tbody>
                </table>

                <%= link_to t('.new', :default => t("helpers.links.neuer_milestone")),
                            "/projectevents/new/#{@project.id}",
                            :class => 'btn btn-primary' %>
            </div>




        <%- model_class = Todo -%>



            <div class="tab-pane fade in " id="todos">
                <h2><%= t '.title', :default => model_class.model_name.human.pluralize %></h2>

                <table class="table table-striped" id="todos">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Status</th>
                        <th>User</th>
                        <th><%= t '.actions', :default => t("helpers.actions") %></th>
                    </tr>
                    </thead>
                    <tbody>

                    <% @todos.each do |todo| %>

                        <tr class="todos" id="todo_<%= todo.id %>">
                            <% if todo.state=="offen"; @badge= "badge-important"; end %>
                            <% if todo.state=="in Arbeit"; @badge= "badge-warning"; end %>
                            <% if todo.state=="fertig"; @badge= "badge-success"; end %>

                            <td>
                                    <span class="badge <%= "#{@badge}" %>">ToDo</span>


                                <%= link_to todo.todotitle, todo_path(todo) %>
                            </td>

                            <td><%= todo.user.firstname %></td>
                            <td><%= todo.state %></td>

                            <td>
                                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                            edit_todo_path(todo), :class => 'btn btn-mini' %>
                                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                            todo_path(todo),
                                            :method => :delete,
                                            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                                            :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>
                      <%end %>



                    </tbody>
                </table>

                <%= link_to t('.new', :default => t("helpers.links.neues Todo")),
                            "/todos/new/#{@project.id}",
                            :class => 'btn btn-primary' %>
            </div>
           </div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>Projekt bearbeiten</h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:all_day) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.title %></td>
        <td><%= project.starts_at %></td>
        <td><%= project.ends_at %></td>
        <td><%= project.all_day %></td>
        <td><%= project.description %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal'} do |f| %>
    <h2>Projekt anzeigen</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
    <dl class="dl-horizontal">
      <dt><strong>Titel: </strong></dt>
      <dd><%= @project.title %></dd>
      <dt><strong>Start-Datum:</strong></dt>
      <dd><%= @project.starts_at.strftime("%d.%m.%y") %></dd>
      <dt><strong>Projekt-Ende:</strong></dt>
      <dd><%= @project.ends_at.strftime("%d.%m.%y") %></dd>
        <dt><strong>Verantwortlich:</strong></dt>
                      <dd><%= @project.user.firstname %></dd>
      <dt><strong>Beschreibung:</strong></dt>
      <dd><%= @project.description %></dd>
      <dt><strong>Projekt-Link:</strong></dt>
      <dd><a href=<%= @project.projectlink %>  target="_blank"><%= @project.projectlink %></a></dd>
    </dl>
    </div>

        <ul id="myTab" class="nav nav-tabs" data-tabs="tabs">
            <li class="active"><a href="#milestones" data-toggle="tab">Milestones</a></li>
            <li><a href="#todos" data-toggle="tab">Todos</a></li>
        </ul>
            <div class="tab-content">
              <div class="tab-pane fade in active" id="milestones">
                <%- model_class2 = Projectevent -%>

                <h3> Project-Milestones</h3>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Milestone</th>
                        <th>Beginn</th>
                        <th>Ende</th>


                    </tr>
                    </thead>

                    <% @projectevents.each do |projectevent| %>

                                <% @badge = "badge" %>
                                <% if projectevent.state=="offen"; @badge= "badge-important"; end %>
                                <% if projectevent.state=="in Arbeit"; @badge= "badge-warning"; end %>
                                <% if projectevent.state=="fertig"; @badge= "badge-success"; end %>

                        <tr>
                            <td>

                                <span class="badge <%= "#{@badge}" %>">Milestone</span> <a href=<%= "/projectevent/#{projectevent.id}" %> ><%= projectevent.title %></a>
                            </td>
                            <td><%= projectevent.starts_at.strftime("%d.%m.%y") %></td>
                            <td><%= projectevent.ends_at.strftime("%d.%m.%y") %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>


            </div>




        <%- model_class = Todo -%>



            <div class="tab-pane fade in " id="todos">
                <h3>ToDos</h3>

                <ul id="todos" data-update-url="<%= sort_todos_url %>">
                   <% @todos.each do |todo| %>
                        <% @badge = "badge" %>
                        <% if todo.state=="offen"; @badge= "badge-important"; end %>
                        <% if todo.state=="in Arbeit"; @badge= "badge-warning"; end %>
                        <% if todo.state=="fertig"; @badge= "badge-success"; end %>
                        <%= content_tag_for :li, todo do %>
                                <span class="badge <%= "#{@badge}" %>">ToDo</span>

                            <%= link_to todo.todotitle, todo_path(todo) %>  /  <%= todo.user.name %>

                       <% end %>


                <% end %>
                </ul>




            </div>
           </div>
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  projects_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_project_path(@project), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  project_path(@project),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>

<% end %>