config/routes.rb
FullcalendarAssets::Application.routes.draw do
  resources :teams

  resources :todos  do
      collection { post :sort }
    end

  resources :projects   do
        collection { post :sort }
      end

  resources :eventitems
  resources :projectevents
  resources :users

  resource :calendar, :only => [:show]

  resource :projectcalendar, :only => [:show]

  resources :events
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "home#index"

  resources :sessions
  resources :password_resets

  match 'projectsearch' => 'projects#search'
  match 'myprojects' => 'projects#my_projects'
  match 'mytodos' => 'todos#my_todos'
  match 'projectcopy/:id' => 'projects#copy'
  match 'projects/:action/:title' => 'projects#index'
  match 'project/show_todos/:id' => 'projects#show_todos'
  match 'project/report/:id' => 'projects#report'
  match 'projects/:id' => 'projects#show'
  match 'projects/:id' => 'projects#sort'
  match 'projectevents/new/:id' => 'projectevents#new'
  match 'projectevent/:id' => 'projectevents#showmilestone'
  match 'todos/new/:id' => 'todos#new'
  match 'todo/:id' => 'todos#show'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "jquery-ui" %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>

        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2></h2>
 <%= image_tag("team_3d.jpg", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/calendars.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>


           <% if current_user %>
                <li><%= link_to "Log Out", logout_path %></li>
             <li> <BR>Logged in as <%= current_user.email %> <%= current_user.team_id %> </li>.

           <% else %>
             <li><%= link_to "Sign Up", signup_path %> or
             <%= link_to "Log In", login_path %>  </li>
           <% end %>


        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Apps-date-icon.png", :align=>'right') %>
          <br/>  <br/><br/><br/> <br/> <br/> <br/>

                  <h2>Team-Kalender </h2>

    </div>
      <div class="span3">
        <div class="btn-group">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            Action
            <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><%= link_to "User bearbeiten", users_path %></li>
                <li><%= link_to "Teams bearbeiten", teams_path %></li>
                <li><%= link_to "Event-Gruppen bearbeiten", eventitems_path %></li>

            <!-- dropdown menu links -->
        </ul>
      </div>
      </div>

  </div>
</div>

</body>
</html>

app/views/layouts/events.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/orig-events.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Kalender", calendar_path %></li>
            <li><%= link_to "User", users_path%></li>
          <li><%= link_to "Projekte", projects_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/orig-projectevents.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Kalender", calendar_path %></li>
            <li><%= link_to "User", users_path%></li>
          <li><%= link_to "Projekte", projects_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/orig-projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Kalender", calendar_path %></li>
            <li><%= link_to "User", users_path%></li>
          <li><%= link_to "Projekte", projects_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/projectcalendars.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
            <%= form_tag "/projectsearch/", :class => "navbar-search pullright", :method => :get do   %>
                                           <%= text_field_tag :title, nil, :class => "search-query span3", :placeholder => "Search"  %>
                                        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">

          <%= image_tag("Apps-date-icon.png", :align=>'right') %>
          <br/>  <br/><br/><br/> <br/> <br/> <br/>
          <h2>Projekt-Kalender </h2>

          <div class="span3">
                  <div class="btn-group">
                      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                      Action
                      <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><%= link_to "meine Projekte", "/myprojects" %></li>
                          <li><%= link_to "Team Projekte", projects_path %></li>
                          <li><%= link_to "meine offenen Todos", "/mytodos" %></li>
                          <li><%= link_to "offene Team Todos", todos_path %></li>
                          <li><%= link_to "User bearbeiten", users_path %></li>
                      <!-- dropdown menu links -->
                  </ul>
                </div>
                </div>


    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/projectevents.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>

        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
            <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
            <%= form_tag "/projectsearch/", :class => "navbar-search pullright", :method => :get do   %>
                                                       <%= text_field_tag :title, nil, :class => "search-query span3", :placeholder => "Search Projekt"  %>
                                                    <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
      <% if @project != nil %>
      <div class="span3">
              <div class="btn-group">
                  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                  Report
                  <span class="caret"></span>
                  </a>

                  <ul class="dropdown-menu">

                      <li><%= link_to "Projekt-Report", "/project/report/#{@project.id}" %></li>


                  <!-- dropdown menu links -->
              </ul>

            </div>
            </div>
      <% end %>
  </div>

</div>

</body>
</html>

app/views/layouts/todos.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rossixTeam</title>
    <div>
    <%= image_tag("rossixSpLogo6.jpg", :align=>'left') %>
    <%= image_tag("rossixTeam.jpg", :align=>'right') %>
    <br /> <br><br><br>
    </div>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">rossixTeam</a>
      <div class="nav-collapse">
        <ul class="nav">
            <li><%= link_to "Kalender", calendar_path %></li>
          <li><%= link_to "Projekt-Kalender", projectcalendar_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>

      <div class="span3">
        <h2> </h2>
 <%= image_tag("Actions-contact-date-icon.png", :align=>'right') %>
    </div>
  </div>
</div>

</body>
</html>